Page({
  data:{
    questionType:1,
    th:1,
    questShow:true,
    questTypeArr:[1,2,3]
  },
  questShift:function(){
    this.setData({
      questShow:false,
      questionType:this.data.questTypeArr[this.data.th],
      th:this.data.th+1
    })
    this.setData({
      questShow:true
    })
  }
})